name: Test, Build, Release

on:
  workflow_dispatch:
    inputs:
      shouldPublish:
        description: 'Publish'
        required: true
        default: true
        type: boolean

jobs:
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: 12
#
#      - name: Install Yarn
#        run: npm install -g yarn
#
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.yarn
#          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.OS }}-node-
#            ${{ runner.OS }}-
#
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#
#      - name: Lint
#        run: yarn lint
#
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Install Node
#        uses: actions/setup-node@v2
#        with:
#          node-version: 12
#
#      - name: Install Yarn
#        run: npm install -g yarn
#
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.yarn
#          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.OS }}-node-
#            ${{ runner.OS }}-
#
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#
#      - name: Test
#        run: yarn test
#
  compile_publish:
#    needs:
#      - lint
#      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Compile
        run: yarn build

      - uses: fregante/setup-git-user@v1

      - name: Set NPM Token
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: ${{ github.event.inputs.shouldPublish == 'true' }}
        run: yarn lerna publish from-package --yes --no-verify-access

